# Generated by Django 4.1.3 on 2022-11-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID',default=1)),
                ('dep_name', models.CharField(max_length=255)),
                ('dep_discription', models.TextField()),
            ],
        ),
    ]
