# Generated by Django 4.1.2 on 2022-11-08 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_rename_dep_discription_department_dep_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='department_description',
            field=models.ForeignKey(default='hey', on_delete=django.db.models.deletion.CASCADE, related_name='d_description', to='hospitalapp.department'),
        ),
    ]
