# Generated by Django 4.1.2 on 2022-11-08 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0007_alter_doctors_department_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='department_description',
            new_name='dep_description',
        ),
        migrations.RenameField(
            model_name='doctors',
            old_name='department_name',
            new_name='dep_name',
        ),
    ]
