# Generated by Django 4.1.2 on 2022-11-08 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0009_alter_doctors_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='dr_name',
        ),
        migrations.DeleteModel(
            name='doctors',
        ),
    ]
