# Generated by Django 4.1.2 on 2022-11-08 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0010_remove_booking_dr_name_delete_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_name', models.CharField(max_length=255)),
                ('dr_spec', models.CharField(max_length=255)),
                ('dr_image', models.ImageField(upload_to='doctors')),
                ('dep_description', models.ForeignKey(default='hey', on_delete=django.db.models.deletion.CASCADE, related_name='d_description', to='hospitalapp.department')),
                ('dep_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d_name', to='hospitalapp.department')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='dr_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.doctors'),
            preserve_default=False,
        ),
    ]
