# Generated by Django 4.1.2 on 2022-11-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0013_alter_department_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='form12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
