# Generated by Django 4.1.2 on 2022-11-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0014_form12'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form12',
            name='phone_number',
            field=models.IntegerField(max_length=255),
        ),
    ]
